### PR TITLE
feat : added custom UI loc : MKT-5565

### PR DESCRIPTION
**Pull request by MaitriGurey1**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=nr26aoK)

Changes : 
1. Added separate routes for app config and custom field 
2. Add CTA and audience list modal 

[UI changes will be handed in separate subtasks]

### CODE REVIEW

**Comment by MaitriGurey1** [comment]
https://github.com/contentstack/extensions/assets/112094917/f958ba9a-e542-4099-9017-5ad6fd00a6c9

**Review by Amitkanswal — CHANGES_REQUESTED** [review]
Pls check that modal issue first

**Comment by MaitriGurey1** [comment]
> Pls check that modal issue first

Hi @Amitkanswal the modal issue is resolved now, 
image

**Comment by Amitkanswal** [comment]
Can you check UI it's not similar to what we have in audience app @MaitriGurey1

**Comment by MaitriGurey1** [comment]
> Can you check UI it's not similar to what we have in audience app @MaitriGurey1

UI changes will be handled in separate subtasks as mentioned in the description @Amitkanswal

**Comment by MaitriGurey1** [comment]
https://github.com/contentstack/extensions/assets/112094917/e6710b34-80cb-47f5-bec2-c133e2632d7b

**Review by Amitkanswal — DISMISSED** [review]

**Review by surajcontentstack — APPROVED** [review]

**Comment by MaitriGurey1** [comment]
Closing this PR as staging branch is avaliable now and creating new PR into staging : https://github.com/contentstack/extensions/pull/266
PR for syncing staging and main branch :
https://github.com/contentstack/extensions/pull/265

**Pull request closed without merging**
